galaxy_info:
  role_name: deploy_baremetal
  namespace: cubepath
  author: CubePath
  description: Deploy baremetal servers on CubePath Cloud
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
dependencies: []
