#!/usr/bin/python
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
module: managed_database_user
short_description: Manage users of a CubePath Managed Database
description:
    - Create or delete a database user of a managed database.
    - The module finds an existing user by I(username). The password of an existing user is never changed.
    - The password, generated by the platform unless I(password) is set, is returned only when the user is created.
    - Creation and deletion are asynchronous. By default the module waits until the user is C(active),
      or gone when I(state=absent).
version_added: "1.5.0"
author: CubePath (@cubepath)
extends_documentation_fragment:
    - cubepathinc.cloud.cubepath
options:
    state:
        description: Desired state of the user.
        type: str
        default: present
        choices: [present, absent]
    managed_database:
        description: Name or UUID of the managed database.
        type: str
        required: true
    username:
        description: User name, up to 32 lowercase letters, digits and underscores, starting with a letter.
        type: str
        required: true
    password:
        description: Password of a new user (12 to 64 characters). Generated by the platform when omitted.
        type: str
    wait:
        description: Wait until the user is C(active), or deleted when I(state=absent).
        type: bool
        default: true
    wait_timeout:
        description: Seconds to wait when I(wait=true).
        type: int
        default: 600
'''

EXAMPLES = r'''
- name: Create an application user
  cubepathinc.cloud.managed_database_user:
    api_token: "{{ cubepath_token }}"
    managed_database: app-db
    username: app_user
  register: app_user
  no_log: true

- name: Remove it
  cubepathinc.cloud.managed_database_user:
    api_token: "{{ cubepath_token }}"
    managed_database: app-db
    username: app_user
    state: absent
'''

RETURN = r'''
user:
    description: User details (C(uuid), C(username), C(status)).
    type: dict
    returned: when I(state=present)
password:
    description: Password of the user. Shown only once, store it.
    type: str
    returned: when the user is created
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.cubepathinc.cloud.plugins.module_utils.cubepath_api import CubePathAPI, cubepath_argument_spec
from ansible_collections.cubepathinc.cloud.plugins.module_utils.cubepath_common import as_list, wait_for
from ansible_collections.cubepathinc.cloud.plugins.module_utils.cubepath_managed_database import require_instance


def main():
    argument_spec = cubepath_argument_spec()
    argument_spec.update(
        state=dict(type='str', default='present', choices=['present', 'absent']),
        managed_database=dict(type='str', required=True),
        username=dict(type='str', required=True),
        password=dict(type='str', no_log=True),
        wait=dict(type='bool', default=True),
        wait_timeout=dict(type='int', default=600),
    )
    module = AnsibleModule(argument_spec=argument_spec, supports_check_mode=True)

    api = CubePathAPI(module)
    username = module.params['username']
    timeout = module.params['wait_timeout']
    md = require_instance(module, api, module.params['managed_database'])
    base = '/managed-databases/%s/users' % md['uuid']

    def fetch():
        return next((u for u in as_list(api.get(base)) if u.get('username') == username), None)

    existing = fetch()

    if module.params['state'] == 'absent':
        if existing is None:
            module.exit_json(changed=False)
        if module.check_mode:
            module.exit_json(changed=True)
        if existing.get('status') != 'deleting':
            api.delete('%s/%s' % (base, existing['uuid']))
        if module.params['wait']:
            wait_for(module, fetch, lambda u: u is None, timeout)
        module.exit_json(changed=True)

    result = {'changed': False}
    if existing is None:
        if module.check_mode:
            module.exit_json(changed=True)
        data = {'username': username}
        if module.params.get('password'):
            data['password'] = module.params['password']
        created = api.post(base, data)
        result['changed'] = True
        result['password'] = created.get('password')
    user = fetch()
    if module.params['wait'] and user and user.get('status') == 'pending':
        user = wait_for(module, fetch, lambda u: u is not None and u.get('status') != 'pending', timeout)
    result['user'] = user
    module.exit_json(**result)


if __name__ == '__main__':
    main()
